---
- hosts:        127.0.0.1
  connection:   local

  tasks:
  - name: Check Sudo Password
    command: ls
    become: yes
    become_method: sudo

  - name: Tap Caskroom
    homebrew_tap: tap=caskroom/cask

  - name: Install Caskroom
    homebrew: name=brew-cask state=latest

  - name: Install Docker Toolbox
    homebrew_cask: name=dockertoolbox state=present
    environment:
      HOMEBREW_CASK_OPTS: --appdir=/Applications
    become: yes
    become_method: sudo

  - name: Install Vagrant
    homebrew_cask: name=vagrant state=present
    become: yes
    become_method: sudo

  - name: Create resolver directory
    file: path=/etc/resolver state=directory mode=0755
    become: yes
    become_method: sudo

  - name: Create dev resolver file at /etc/resolver/dev
    file: >
      src={{root_dir}}/ansible/resolver-dev.conf
      dest=/etc/resolver/dev
      state=link
      force=yes
    become: yes
    become_method: sudo

  - name: Add NFS share to /etc/exports
    lineinfile:
      dest: /etc/exports
      line: "{{ item }}"
      create: yes
    with_items:
      - '\"/Users\" 192.168.99.100 -alldirs -mapall=0:80'
    become: yes
    become_method: sudo
    register: exports

  - name: Restart nfsd
    command: sudo nfsd restart
    become: yes
    become_method: sudo
    when: exports.changed

  - name: Add Docker Machine Environment to .bash_profile
    lineinfile:
      dest: ~/.bash_profile
      line: "source {{ root_dir }}/ansible/profile"
      create: yes
    when: ansible_env.SHELL == "/bin/bash"

  - name: Create and configure docker machine
    command: sh {{root_dir}}/docker/docker_machine_setup.sh {{root_dir}} creates=~/.docker/machine/machines/dev/config.json
