---
- hosts:        127.0.0.1
  connection:   local

  tasks:
  - name: Check Sudo Password
    command: ls
    become: yes
    become_method: sudo

  - name: Tap Caskroom
    homebrew_tap: tap=caskroom/cask

  - name: Install Caskroom
    homebrew: name=brew-cask state=latest

  - name: Install Docker Toolbox
    homebrew_cask: name=dockertoolbox state=present
    environment:
      HOMEBREW_CASK_OPTS: --appdir=/Applications
    become: yes
    become_method: sudo

  - name: Create resolver directory
    file: path=/etc/resolver state=directory mode=0755
    become: yes
    become_method: sudo

  - name: Create dev resolver file at /etc/resolver/dev
    file: >
      src={{root_dir}}/ansible/resolver-dev.conf
      dest=/etc/resolver/dev
      state=link
      force=yes
    become: yes
    become_method: sudo

  - name: Create and configure docker machine
    command: sh {{root_dir}}/docker/docker_machine_setup.sh {{root_dir}} creates=~/.docker/machine/machines/dev/config.json

  - name: Start base docker compose
    command: docker-compose -f {{root_dir}}/docker/base_docker_compose.yml -p bootx up -d 
